stages:
    - style
    - test
    - deploy
    - release

pep8:
    stage: style
    script:
        - echo "执行了代码风格检查"
    # 选择 执行这个 jobs的 runner
    tags:
        - firstrunner
    # only 指定 只有 干什么的时候才执行，except 指定 干什么的时候不执行
    except:
        - tags

unittest:
    stage: test
    script:
        - echo "执行单元测试"
    tags:
        - firstrunner
    except:
        - tags

dockercompose-deploy:
    stage: deploy
    script:
        - echo "部署测试"
    tags:
        - firstrunner
    # 指定只有 Master 合并的时候才 执行
    only:
        - master

docker-release:
    stage: release
    script:
        - echo "版本上线"
    tags:
        - firstrunner
    only:
        - tags



