language: python
services:
- docker
python:
- '3.6'

addons:
    ssh_known_hosts:
        - 112.74.33.223   
before_install:
    - openssl aes-256-cbc -K $encrypted_8cc0db86b412_key -iv $encrypted_8cc0db86b412_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d

stages:
- styletest
- unittest
- name: deploy
  if: branch=master
- name: release
  if: branch=master
jobs:
  include:
  - stage: styletest
    script: echo "style test"
  - stage: unittest
    script: echo "unit test"
  - stage: deploy
    script: ssh travis@112.74.33.223 -o StrictHostKeyChecking=no 'cd ~/flask-myblog && git pull && docker-compose up'
  - stage: release
    script: echo "release"


