language: python
services: 
    - docker 
python:
    - "3.7"

stages:
    - styletest
    - unittest
    - deploy
    - release

jobs:
    include:
        - stage: styletest
          script: echo "style test"
        - stage: unittest
          script: echo "unit test"
        - stage: deploy
          script: echo "deploy"
        - stage: release
          script: echo "release"
    
